title: GHTNS
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ghtns.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jalangle

# Build settings
markdown: kramdown
theme: minima

collections:
  hikes:
    output: true
    markdown: kramdown
    theme: minima
  visit:
    output: true
    markdown: kramdown
    theme: minima

defaults:
  - scope:
      path: ""
      type: "hikes"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "visit"
    values:
      layout: "page"
